version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: taskflow_db
    environment:
      POSTGRES_USER: taskflow_admin
      POSTGRES_PASSWORD: supersecretpassword
      POSTGRES_DB: taskflow_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: